src/apps/web/urls.py
from django.conf.urls import url
from .views import (home, nuestra_historia, quienes_somos, mision_vision_valores,
 equipamiento, ajax_equipamiento_modal, servicios, clientes, trabajos, contacto, contacto_ajax,
 servicios_detalle)

app_name = 'web'

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^nuestra-historia/$', nuestra_historia, name='nuestra_historia'),
    url(r'^quienes-somos/$', quienes_somos, name='quienes_somos'),
    url(r'^mision-vision-valores/$', mision_vision_valores, name='mision_vision_valores'),
    url(r'^equipamiento/$', equipamiento, name='equipamiento'),
    url(r'^equipamiento-ajax/$', ajax_equipamiento_modal, name='ajax_equipamiento_modal'),
    url(r'^servicios/$', servicios, name='servicios'),
    url(r'^servicios-detalle/(?P<slug>[-\w]+)/$', servicios_detalle, name='servicios_detalle'),

    url(r'^trabajos/$', trabajos, name='trabajos'),
    url(r'^clientes/$', clientes, name='clientes'),
    url(r'^contacto/$', contacto, name='contacto'),
    url(r'^contacto-ajax/$', contacto_ajax, name='contacto_ajax'),


]

src/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from filebrowser.sites import site
from ckeditor_uploader import urls as ck_urls


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^ckeditor/', include(ck_urls)),


] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
urlpatterns += i18n_patterns('',
    url(r'', include('apps.web.urls', namespace='web')),
    )
handler404 = 'apps.web.views.page_404'
handler500 = 'apps.web.views.page_500'

src/templates/common/_base.html
{% load static %}
{% load seo %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
     {% metatags %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->


    <!-- Bootstrap -->
    <link href=" {% static "css/bootstrap.min.css" %} " rel="stylesheet">
    <link rel="stylesheet" href=" {% static "css/font-awesome.min.css" %}">
    <link rel="stylesheet" href=" {% static "css/animate.css" %} ">
    <link href=" {% static "css/animate.min.css" %}" rel="stylesheet">
    <link href=" {% static "css/style.css" %} " rel="stylesheet" />
    <link href=" {% static "css/dev.css" %} " rel="stylesheet" />
     <link rel="stylesheet" type="text/css" href="{% static "css/languages.min.css" %}">


<video autoplay loop muted id="background">
<source src="{{infosite.video.url}}" type="video/mp4">
</video>

    {% block cssadicional %}
    {% endblock %}
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
        {% include "common/_header.html" %}
        <div class="container">
            <div class="col-md-12">

                    <img src="{{ infosite.logo_empresa.url }}" alt="" class="img-responsive"/>


            </div>
    </div>
        {% block content %}

        {% endblock content %}


    {% include "common/_footer.html" %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src=" {% static "js/jquery.js" %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src=" {% static "js/bootstrap.min.js" %}"></script>
    <script src=" {% static "js/wow.min.js" %}"></script>
    {% block jsfinal %}

    {% endblock %}
    <script type="text/javascript">
        var url = window.location.pathname,
        urlRegExp = new RegExp(url.replace(/\/$/,'') + "$");
        $('#navbar a').each(function(){
            if(urlRegExp.test(this.href.replace(/\/$/,''))){
                $(this).parents().addClass('active');
            }
        });

        // ADD ACTIVE TO LANGUAGE
        url_splitted= window.location.href.split('/')
        console.log(url_splitted);
        if (url_splitted[3] == 'es'){
            console.log('IF')
            $('#en').removeClass('active')
            $('#es').addClass('active')
        }else{
            console.log('else')
            $('#en').addClass('active')
            $('#es').removeClass('active')
        }



    </script>
  </body>
</html>

src/templates/common/_email.html
{% spaceless %}
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">

<html lang="es">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>{% block title %}{% endblock %} | {{ info.titulo }}</title>

  <style>
  a:hover {
    text-decoration: underline !important;
  }

  td.contentblock h4 {
    color:#444444 !important;
    font-size:16px;
    line-height:24px;
    font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;
    margin-top:0;
    margin-bottom:10px;
    padding-top:0;
    padding-bottom:0;
    font-weight:normal;
  }
  td.contentblock h4 a {
    color:#444444;
    text-decoration:none;
  }
  td.contentblock p {
      color:#888888;
    font-size:13px;
    line-height:19px;
    font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;
    margin-top:0;
    margin-bottom:12px;
    padding-top:0;
    padding-bottom:0;
    font-weight:normal;
  }
  td.contentblock p a {
      color:#3ca7dd;
    text-decoration:none;
  }
  @media only screen and (max-device-width: 480px) {
       div[class="header"] {
            font-size: 16px !important;
       }
       table[class="table"], td[class="cell"] {
            width: 300px !important;
       }

    td[class="footershow"] {
            width: 300px !important;
       }
    table[class="hide"], img[class="hide"], td[class="hide"] {
            display: none !important;
       }
       img[class="divider"] {
          height: 1px !important;
     }
     td[class="logocell"] {
      padding-top: 15px !important;
      padding-left: 15px !important;
      width: 300px !important;
     }
       img[id="screenshot"] {
            width: 325px !important;
            height: 127px !important;
       }
    img[class="galleryimage"] {
        width: 53px !important;
            height: 53px !important;
    }
    p[class="reminder"] {
      font-size: 11px !important;
    }
    h4[class="secondary"] {
      line-height: 22px !important;
      margin-bottom: 15px !important;
      font-size: 18px !important;
    }
  }

  </style>
</head>

<body bgcolor="#e4e4e4" topmargin="0" leftmargin="0" marginheight="0" marginwidth="0" style="-webkit-font-smoothing: antialiased;width:100% !important;background:#e4e4e4;-webkit-text-size-adjust:none;">

<table width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#e4e4e4">
<tr>
  <td bgcolor="#e4e4e4" width="100%">

  <table width="600" cellpadding="0" cellspacing="0" border="0" align="center" class="table">
  <tr>
    <td width="600" class="cell">

      <table width="600" cellpadding="0" cellspacing="0" border="0" class="table">
    <tr>
      <td width="250" bgcolor="#e4e4e4" class="logocell">
        <img border="0" src="{% static 'images-email/spacer.gif' %}" width="1" height="20" class="hide"><br class="hide">{% block logo %}{% endblock %}
        <br><img border="0" src="{% static 'images-email/spacer.gif' %}" width="1" height="10" class="hide"><br class="hide"></td>
        <td align="right" width="350" class="hide" style="color:#a6a6a6;font-size:12px;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;text-shadow: 0 1px 0 #ffffff;" valign="top" bgcolor="#e4e4e4"><img border="0" src="{% static 'images-email/spacer.gif'%}" width="1" height="63"><br><span>{{ info.titulo|upper }}</span><strong>
        <span style="text-transform:uppercase;"> </span></strong>
      </td>
    </tr>
    </table>

    <repeater>
      <layout label="New feature">
      <table width="100%" cellpadding="0" cellspacing="0" border="0">
      <tr>
        <td bgcolor="#85bdad" nowrap><img border="0" src="{% static 'images-email/spacer.gif' %}" width="5" height="1"></td>

        <td width="100%" bgcolor="#ffffff">

          <table width="100%" cellpadding="20" cellspacing="0" border="0">
          <tr>
            <td bgcolor="#ffffff" class="contentblock">
                {% block content %}{% endblock %}

            </td>
          </tr>
          </table>

        </td>
      </tr>
      </table>
      <img border="0" src="{% static 'images-email/spacer.gif' %}" width="1" height="15" class="divider"><br>
      </layout>
    </repeater>

    </td>
  </tr>
  </table>
  </td>
</tr>
</table>

</body>
</html>
{% endspaceless %}

src/templates/common/_footer.html
  <footer class="footer_dev">
        <div class="container">
            <div class="col-md-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                <h4 class="title_footer">Contacto</h4>

                <div class="contact-info">
                    <ul>
                    {% if infosite.direccion %}
                        <li><i class="fa fa-home fa"></i> &nbsp;{{infosite.direccion}}</li>
                    {% endif %}

                    {% if infosite.telefono %}
                        <li><i class="fa fa-phone fa"></i> &nbsp; {{infosite.telefono}}</li>
                    {% endif %}

                    {% if infosite.email %}
                                 <li><i class="fa fa-envelope fa"></i> &nbsp;{{infosite.email}}</li>
                    {% endif %}

                    </ul>
                </div>
            </div>
            <div class="col-md-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">

            </div>


        </div>
    </footer>

    <div class="sub_footer_dev">
        <div class="container">
            <div class="social-icon">
                <div class="col-md-4">
                    <ul class="social-network">
                    {% if infosite.facebook %}
                                <li><a href="{{infosite.facebook}}" target="_blank" class="fb tool-tip" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                    {% endif %}

                    {% if  infosite.twitter%}
                        <li><a href="{{infosite.twitter}}" target="_blank" class="twitter tool-tip" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                    {% endif %}

                    {% if infosite.gmail %}
                            <li><a href="{{infosite.gmail}}"  target="_blank" class="gplus tool-tip" title="Google Plus"><i class="fa fa-google-plus"></i></a></li>
                    {% endif %}
                    {% if infosite.linkedin %}
                         <li><a href="{{infosite.linkedin}}" target="_blank"  class="linkedin tool-tip" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                    {% endif %}
                    {% if  infosite.youtube%}
                            <li><a href="{{infosite.youtube}}"  target="_blank" class="ytube tool-tip" title="You Tube"><i class="fa fa-youtube-play"></i></a></li>
                    {% endif %}

                    </ul>
                </div>
            </div>

            <div class="col-md-4 col-md-offset-4">
                <div class="copyright">
                    &copy;  2016 <a target="_blank"  title="Free Twitter Bootstrap WordPress Themes and HTML templates">HyD</a>.All Rights Reserved.
                </div>

            </div>
        </div>
    </div>

src/templates/common/_header.html
<header id="header">
                <nav class="navbar navbar-default navbar-static-top header_dev">
                  <div class="container menu2">
                    <div class="navbar-header">
                      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button>

                    </div>
                    <div id="navbar" class="navbar-collapse collapse">
                      <ul class="nav navbar-nav">
                        <li><a href="{% url 'web:home' %}">Principal</a></li>
                        <li class="dropdown">
                          <a href="#" class="dropdown-toggle menu2-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Nosotros <span class="caret"></span></a>
                          <ul class="dropdown-menu">
                            <li ><a href="{% url 'web:nuestra_historia' %}" >Historia</a></li>
                            <li><a href="{% url 'web:quienes_somos' %}">Quienes somos</a></li>
                            <li><a href="{% url 'web:mision_vision_valores' %}">Mision/Vision/Valores</a></li>
                          </ul>
                        </li>
                        <li><a href="{% url 'web:equipamiento' %}">Equipamiento</a></li>
                        <li><a href="{% url 'web:servicios' %}">Servicios</a></li>

                        {% if  infosite.activar_trabajo%}
                          <li><a href="{% url 'web:trabajos' %}">Trabajos</a></li>
                        {% endif %}

                        {% if infosite.activar_clientes %}
                        <li><a href="{% url 'web:clientes' %}">Clientes</a></li>
                        {% endif %}

                        <li><a href="{% url 'web:contacto' %}">Contacto</a></li>
                      </ul>

                      {% if infosite.activar_idiomas %}


                      <ul class="nav navbar-nav navbar-right">

                        <li id="es"><a href="/es/"><span class="lang-sm lang-lbl" lang="es"></a></li>
                        <li id="en"><a href="/en/"><span class="lang-sm lang-lbl" lang="en"></span></a></li>
                      </ul>
               {% endif %}
                    </div><!--/.nav-collapse -->
                  </div>
                </nav>
    </header><!--/header-->