src/apps/web/urls.py
from django.conf.urls import url
from .views import (home, nuestra_historia, quienes_somos, mision_vision_valores,
 equipamiento, ajax_equipamiento_modal, servicios, clientes, trabajos, contacto, contacto_ajax,
 servicios_detalle)

app_name = 'web'

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^nuestra-historia/$', nuestra_historia, name='nuestra_historia'),
    url(r'^quienes-somos/$', quienes_somos, name='quienes_somos'),
    url(r'^mision-vision-valores/$', mision_vision_valores, name='mision_vision_valores'),
    url(r'^equipamiento/$', equipamiento, name='equipamiento'),
    url(r'^equipamiento-ajax/$', ajax_equipamiento_modal, name='ajax_equipamiento_modal'),
    url(r'^servicios/$', servicios, name='servicios'),
    url(r'^servicios-detalle/(?P<slug>[-\w]+)/$', servicios_detalle, name='servicios_detalle'),

    url(r'^trabajos/$', trabajos, name='trabajos'),
    url(r'^clientes/$', clientes, name='clientes'),
    url(r'^contacto/$', contacto, name='contacto'),
    url(r'^contacto-ajax/$', contacto_ajax, name='contacto_ajax'),


]

src/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from filebrowser.sites import site
from ckeditor_uploader import urls as ck_urls


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^ckeditor/', include(ck_urls)),


] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
urlpatterns += i18n_patterns('',
    url(r'', include('apps.web.urls', namespace='web')),
    )
handler404 = 'apps.web.views.page_404'
handler500 = 'apps.web.views.page_500'

src/apps/web/models.py
# -*- coding: utf-8 -*-
from urlparse import urlparse

from django.db import models
from django.conf import settings
from django.contrib.sites.models import Site
from django.core.urlresolvers import reverse

from geoposition.fields import GeopositionField
from filebrowser.fields import FileBrowseField
from ckeditor.fields import RichTextField


from apps.core.models import AuditableModel, SlugModel, PositionModel


class InfoSite(AuditableModel):
    site = models.CharField("URL del sitio", max_length=60, blank=True,
        help_text='Ingrese la url actual del sitio sin el slash final')

    ga = models.CharField('Google Analytics', max_length=24, blank=True,
       help_text='''Opcional: Inserte el código que Google Analytics le
       proporciona con el formato: UA-XXXXX-X''')
    video = FileBrowseField('Video secciones', max_length=700,
        directory='infosite', extensions=['.mp4', '.avi', '.mpg'],
        help_text=u'Videos en formato mp4, avi, mpg')

    activar_idiomas = models.BooleanField(default=True)
    activar_trabajo = models.BooleanField(default=True)
    activar_clientes = models.BooleanField(default=True)

    telefono = models.CharField('Teléfono', max_length=120, blank=True)
    email = models.CharField('Email', max_length=120, blank=True)
    direccion = models.CharField('Dirección', max_length=120, blank=True)
    logo_empresa = FileBrowseField('Logo de la empresa', max_length=700,
        directory='infosite', extensions=['.jpg', '.png', '.gif'],
        help_text=u'Tamaño recomendado:1110x137')
    # formulario contacto
    email_contacto = models.EmailField('Email Contacto', blank=True, null=True, help_text='A este email llegarán los formularios de contacto')
    # REDES SOCIALES
    facebook = models.URLField('Facebook', blank=True)
    linkedin = models.URLField('Linkedin', blank=True)
    gmail = models.URLField('Gmail', blank=True)
    youtube = models.URLField('youtube', blank=True)
    twitter = models.URLField('Twitter', blank=True)
    coordenadas = GeopositionField('Coordenadas')

    def __unicode__(self):
        return u'Información del Sitio'

    class Meta:
        verbose_name_plural = u'Información del Sitio'

    def save(self, *args, **kwargs):
        site = Site.objects.get(id=settings.SITE_ID)
        site.domain = urlparse(self.site).netloc
        site.name = settings.PROJECT_NAME
        site.save()
        super(InfoSite, self).save(*args, **kwargs)


class Home(models.Model):
    titulo_bienvenida = models.CharField('Título de bienvenida', max_length=100)
    texto_bienvenida = RichTextField('Texto de Bienvenida')

    def __unicode__(self):
        return u'Home'

    class Meta:
        verbose_name = 'Home'
        verbose_name_plural = 'Home'


class SeccionServicios(models.Model):
    titulo_seccion_servicios = models.CharField('Titulo servicios', max_length=100)
    texto_servicios = RichTextField('Texto servicios')

    def __unicode__(self):
        return u'Sección servicios'

    class Meta:
        verbose_name = 'Sección servicios'
        verbose_name_plural = 'Sección servicios'


class Servicios(SlugModel, PositionModel):
    descripcion_servicio = RichTextField('Descripción servicios', blank=True, null=True)
    imagen_principal = FileBrowseField('Imagen principal del servicio', max_length=700,
        directory='servicios', extensions=['.jpg', '.png', '.gif'],
        help_text=u'Tamaño recomendado:345x250')

    def get_absolute_url(self):
        return reverse('web:servicios_detalle', kwargs={'slug': self.slug})

    def __unicode__(self):
        return unicode(self.nombre)

    class Meta:
        verbose_name = 'Servicio'
        verbose_name_plural = 'Servicios'
        ordering = ['position']


class ImagenesServicio(PositionModel):
    fk_servicio = models.ForeignKey(Servicios)
    titulo_imagen = models.CharField('Título Imagen', max_length=100)
    imagen = FileBrowseField('Imagen', max_length=700,
        directory='imagenes_servicios', extensions=['.jpg', '.png', '.gif'],
        help_text=u'Tamaño recomendado:345x266')

    def __unicode__(self):
        return self.titulo_imagen

    class Meta:
        verbose_name = 'Imagen Servicio'
        verbose_name_plural = 'Imagenes Servicios'
        ordering = ['position']


class NuestraHistoria(models.Model):
    titulo = models.CharField('Título Historia', max_length=100)
    texto = RichTextField('Texto')

    def __unicode__(self):
        return u'Nuestra Historia'

    class Meta:
        verbose_name = 'Nuestra Historia'
        verbose_name_plural = 'Nuestra Historia'


class QuienesSomos(models.Model):
    titulo_quienes_somos = models.CharField('Título quiénes somos', max_length=80)
    texto_quienes_somos = RichTextField('Texto quienes somos', blank=True, null=True)
    titulo_nuestros_socios = models.CharField('Título nuestros socios', max_length=80)
    texto_nuestros_socios = RichTextField('Texto nuestros socios', blank=True, null=True)

    def __unicode__(self):
        return u'Quienes Somos'

    class Meta:
        verbose_name = 'Quienes Somos'
        verbose_name_plural = 'Quienes Somos'


class OtrosPuestos(PositionModel):
    CHOICES_BLOQUES = (
        ('IZQUIERDO', 'IZQUIERDO'),
        ('DERECHO', 'DERECHO')
    )
    fk_quienes_somos = models.ForeignKey(QuienesSomos)
    titulo_puesto = models.CharField('Puesto', max_length=100)
    bloque = models.CharField('Bloque',  choices=CHOICES_BLOQUES, max_length=100)

    def __unicode__(self):
        return self.titulo_puesto

    class Meta:
        verbose_name = 'Puesto'
        verbose_name_plural = 'Puestos'
        ordering = ['position']


class SeccionPoliticas(models.Model):
    titulo_mision = models.CharField('Título misión', max_length=50)
    texto_mision = RichTextField('Texto misión')
    titulo_vision = models.CharField('Título vision', max_length=50)
    texto_vision = RichTextField('Texto vision')
    titulo_politicas_ambientales = models.CharField('Titulo políticas ambientales', max_length=100)
    texto_politicas_ambientales = RichTextField('Texto políticas embientales', blank=True, null=True)
    pdf = FileBrowseField('PDF', max_length=700,
            directory='pdf', extensions=['.doc', '.docx', '.pdf'],
            help_text=u'Suba solamente archivos en formato  doc, docx y pdf')

    def __unicode__(self):
        return u'Mision / Vision / Políticas'

    class Meta:
        verbose_name = 'Mision / Vision / Políticas'
        verbose_name_plural = 'Mision / Vision / Políticas'


class Valores(PositionModel):
    titulo_valor = models.CharField('Título valor', max_length=80)
    texto_valor = RichTextField('Texto valor')
    imagen_valor = FileBrowseField('Imagen valor', max_length=700,
        directory='valores', extensions=['.jpg', '.png'],
        help_text=u'Tamaño recomendado:46x43')

    def __unicode__(self):
        return self.titulo_valor

    class Meta:
        verbose_name = 'Valor'
        verbose_name_plural = 'Valores'


class Socios(PositionModel):
    nombre = models.CharField('Nombre', max_length=100)
    puesto = models.CharField('Puesto', max_length=80)
    imagen = FileBrowseField('Imagen categoría del trabajo', max_length=700,
        directory='socios', extensions=['.jpg', '.png', '.gif'],
        help_text=u'Tamaño recomendado:406x320')
    cv = FileBrowseField('CV', max_length=700,
        directory='cv', extensions=['.doc', '.docx', '.pdf'],
        help_text=u'Suba solamente archivos en formato  doc, docx y pdf')

    def __unicode__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Socio'
        verbose_name_plural = 'Socios'
        ordering = ['position']


class Logros(PositionModel):
    fk_socio = models.ForeignKey(Socios)
    logro = models.CharField('Logro', max_length=80)

    def __unicode__(self):
        return self.logro

    class Meta:
        verbose_name = 'Logro'
        verbose_name_plural = 'Logros'
        ordering = ['position']


class Equipamiento(PositionModel):
    CHOICES_BLOQUES = (
            ('izquierdo', 'izquierdo'),
            ('central', 'central'),
            ('derecho', 'derecho')
        )

    bloque = models.CharField('Elegir bloque', max_length=100, choices=CHOICES_BLOQUES)
    equipamiento = models.CharField('Equipamiento', max_length=200)

    def contain_detalle(self):
        return self.detalleequipamiento_set.all()

    def __unicode__(self):
        return str(self.pk)

    class Meta:
        verbose_name = 'Equipamiento'
        verbose_name_plural = 'Equipamientos'
        ordering = ['position']


class DetalleEquipamiento(PositionModel):
    fk_equipamiento = models.ForeignKey(Equipamiento, blank=True, null=True)
    detalle_equipamiento = models.CharField('Detalle equipamiento', max_length=100)

    def __unicode__(self):
        return self.detalle_equipamiento

    class Meta:
        verbose_name = 'Detalle Equipamiento'
        ordering = 'Position'
        ordering = ['position']


class SeccionTrabajo(models.Model):
    titulo_trabajo = models.CharField('Título trabajo', max_length=100)
    texto = RichTextField('Texto Trabajo')

    def __unicode__(self):
        return u'Sección Trabajo'

    class Meta:
        verbose_name = 'Sección Trabajo'


class Trabajo(PositionModel):
    titulo_trabajo = models.CharField('Título trabajo', max_length=100)
    text_trabajo = RichTextField('Texto Trabajo', blank=True, null=True)

    def __unicode__(self):
        return self.titulo_trabajo

    class Meta:
        verbose_name = u'Trabajo'
        verbose_name_plural = u'Trabajos'
        ordering = ['position']


class ImagenTrabajos(PositionModel):
    fk_trabajo = models.ForeignKey(Trabajo)
    titulo_trabajo = models.CharField('Título de la imagen', max_length=100)
    imagen_trabajo = FileBrowseField('Imagen del trabajo', max_length=700,
        directory='trabajos', extensions=['.jpg', '.png', '.gif'],
        help_text=u'Tamaño recomendado:445x320')

src/templates/web/categorias_trabajo.html
{% extends "common/_base.html" %}
    {% load static %}
    {% load thumbnail %}
    {% block content %}


<div class="gallery">
        <div class="text-center">
            <h2 class="title_dev">Conosca los trabajos de Myp SAC.</h2>
            <p  class="parrafo_dev">Operaciones Submarinas MyP SAC. Formaliza su organización e infraestructura al tipo de proyecto encomendado conforme a sus avances y logros.
            Sus procedimientos se van complementando y mejorando a medida que la experiencia nos indica la forma mas óptima de desarrollar los trabajos actuando dentro de las más estrictas normas de seguridad, priorizando la seguridad de nuestro personal logrando de esta manera la plena satisfacción de nuestros clientes.
            </p>
        </div>
        <div class="container">
            <div class="col-md-4">
                <figure class="effect-marley">
                    <img src=" {% static "img/servicio1.jpg" %}" alt="" class="img-responsive" style="    width: 345px; height: 266px;" />
                    <figcaption>
                        <p>Mantenimiento y reparación de estructuras submarinas.</p>
                    </figcaption>
                </figure>
            </div>
            <div class="col-md-4">
                <figure class="effect-marley">
                    <img src="{% static "img/puerto.jpg" %}" alt="" class="img-responsive" style="    width: 345px;  height: 266px;" />
                    <figcaption>
                        <!--
                        <h4>sweet marley</h4>
                        -->
                        <p>Mantenimiento y reparación de  Muelles e instalaciones Porturias.</p>
                    </figcaption>
                </figure>
            </div>
            <div class="col-md-4">
                <figure class="effect-marley">
                    <img src="{% static "img/tubos.jpg" %} " alt="" class="img-responsive" style="width: 345px;  height: 266px;"/>
                    <figcaption>
                        <!--
                        <h4>sweet marley</h4>
                        -->
                        <p>Operación en Lagos, Ríos y Otros.</p>
                    </figcaption>
                </figure>
            </div>
        </div>
    </div>
    {% endblock content %}

src/templates/web/clientes.html
{% extends "common/_base.html" %}
{% load static %}
{% load thumbnail %}

{% block content %}

<div class="gallery">
        <div class="text-center">
            <h2 class="title_dev">{{seccion_cliente.titulo_seccion_clientes}}</h2>
            <div   class="parrafo_dev">
                    {{seccion_cliente.texto|safe}}
            </div>

        </div>


        <div class="container">

        {% for cliente in clientes %}

            <div class="col-md-2">
                <figure class="effect-marley">
                    <img src="{{cliente.imagen_logo.path|thumbnail_by_name:'200x150'}}" alt="" class="img-responsive"  style="width: 200px;  height: 150px;" />
                    <figcaption>
                        <p>{{cliente.nombre}}</p>
                    </figcaption>
                </figure>
            </div>

        {% endfor %}

        </div>
    </div>

{% endblock content %}

{% block js_adicional %}

      <script type="text/javascript">

        $(document).ready(function() {
            console.log('HOLA MUNDO');

        });
        </script>
{% endblock js_adicional %}

src/templates/web/contact.html
{% extends "common/_base.html" %}
{% load static %}

{% block content %}

<br>
<br>
<br>

	<div class="map">
		<iframe
                  width="600"
                  height="450"
                  frameborder="0" style="border:0"
                  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDQGOtynZri4OVPaZ7xXdBF1Y4gJVbpt_E&q={{infosite.coordenadas.latitude|stringformat:'.5f'}}, {{infosite.coordenadas.longitude|stringformat:'.5f'}}&center={{infosite.coordenadas.latitude|stringformat:'.5f'}}, {{infosite.coordenadas.longitude|stringformat:'.5f'}}
                    &zoom=18" allowfullscreen>
                </iframe>
	</div>

<section class="contact-page" style='background: none;'>
        <div class="container">
            <div class="text-center">
                <h2 class="title_dev">Escribe tu mensaje  </h2>

            </div>
            <div class="row contact-wrap">
                <div class="status alert alert-success" style="display: none"></div>
                <form id="main-contact-form" class="contact-form" name="contact-form" method="post" action="#">
                {% csrf_token %}
                    <div class="col-sm-5 col-sm-offset-1">
                        <div class="form-group">
                            <label class="label_contacto" >Nombres *</label>
                            <input type="text" name="nombres" class="form-control" required="required">
                        </div>
                        <div class="form-group">
                            <label class="label_contacto">Email *</label>
                            <input type="email" name="email" class="form-control" required="required">
                        </div>
                        <div class="form-group">
                            <label class="label_contacto">Teléfono</label>
                            <input type="number" class="form-control" name="telefono">
                        </div>
                        <div class="form-group">
                            <label class="label_contacto">Compañia</label>
                            <input type="text" class="form-control" name="compania">
                        </div>
                    </div>
                    <div class="col-sm-5">
                        <div class="form-group">
                            <label class="label_contacto">Asunto *</label>
                            <input type="text" name="asunto" class="form-control" required="required">
                        </div>
                        <div class="form-group">
                            <label class="label_contacto">Mensaje *</label>
                            <textarea name="mensaje" id="message" required="required" class="form-control" rows="8"></textarea>
                        </div>
                        <div class="form-group">
                            <button type="submit" name="submit" class="btn btn-info btn_dev btn-lg" required="required" id="enviar">Enviar</button>
                        </div>
                    </div>
                </form>
            </div><!--/.row-->
        </div><!--/.container-->
    </section><!--/#contact-page-->

<div class="modal fade" tabindex="-1" role="dialog" id='myModal'>
  <div class="modal-dialog" style="max-width: 1000px; width:auto;">
    <div class="modal-content modal-color">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="title_dev2">GRACIAS</h4>
      </div>
      <div class="modal-body">
            <p>Le responderemos lo más pronto posible.</p>
      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


{% endblock content %}

{% block jsfinal %}

      <script type="text/javascript">
      console.log('HOLA MUNDO')
        $(document).ready(function() {
            $.fn.serializeObject = function() {
                var o = {};
                var a = this.serializeArray();
                $.each(a, function() {
                    if (o[this.name]) {
                        if (!o[this.name].push) {
                            o[this.name] = [o[this.name]];
                        }
                        o[this.name].push(this.value || '');
                    } else {
                        o[this.name] = this.value || '';
                    }
                });
                return o;
            };
            console.log('HOLA MUNDO');
            $('#enviar').on('click', function(e){
                e.preventDefault();
                form_contact = $('#main-contact-form').serializeObject();
                console.log(form_contact);
                $.ajax({
                            url: '{% url "web:contacto_ajax" %}',
                            type:'post',
                            data: form_contact,

                            success: function(data){
                                if (data['msg'] == 'GRACIAS'){
                                    console.log('GRACIAS')
                                    $('#myModal').modal('show');

                                }
                            }
                });
            });

        });
        </script>
{% endblock jsfinal %}



src/templates/web/email-contacto.html
{% extends "common/_email.html" %}
{% load static %}

{% block title %}Contacto{% endblock %}


{% block logo %}

    <img src="{{infosite.logo_empresa.url}}" alt="-" style="-ms-interpolation-mode:bicubic;">

{% endblock %}


{% block content %}

    <h4 class="secondary">
        <strong>Mensaje de Contacto</strong>
        </h4>
        <p>Han enviado el siguiente formulario:</p>

      <table cellspacing="10" style="width:100%;" id='table_contacto'>
        <tbody>
          <tr>
            <td style='width: 20%;'>
              <strong>Nombres: </strong>
            </td>
            <td>{{ nombres }}</td>
          </tr>
          <tr>
            <td style='width: 20%;'>
              <strong>Teléfono: </strong>
            </td>
            <td>{{ telefono }}</td>
          </tr>
          <tr>
            <td style='width: 20%;'>
              <strong>Email: </strong>
            </td>
            <td>{{ email }}</td>
          </tr>
          <tr>
            <td style='width: 20%;'>
              <strong>Compañia: </strong>
            </td>
            <td>{{ compania }}</td>
          </tr>
          <tr>
            <td style='width: 20%;'>
              <strong>Asunto: </strong>
            </td>
            <td>{{ asunto }}</td>
          </tr>
          <tr>
            <td style='width: 20%;'>
              <strong>Mensaje: </strong>
            </td>
            <td>{{ mensaje }}</td>
          </tr>
        </tbody>
      </table>

{% endblock %}

src/templates/web/equipamiento.html
{% extends "common/_base.html" %}
{% load static %}

{% block content %}


<div class="gallery">
        <div class="text-center">
            <h2 class="title_dev">Relacion de Equipo de la empresa</h2>
            <!--
            <p  class="parrafo_dev">Operaciones Submarinas MyP SAC. Formaliza su organización e infraestructura al tipo de proyecto encomendado conforme a sus avances y logros.
            Sus procedimientos se van complementando y mejorando a medida que la experiencia nos indica la forma mas óptima de desarrollar los trabajos actuando dentro de las más estrictas normas de seguridad, priorizando la seguridad de nuestro personal logrando de esta manera la plena satisfacción de nuestros clientes.
            </p>
            -->
        </div>

        <div class="container" style='text-color:black;'>

            <div class="col-md-4">
                <ul class = "list-group">
                    {% for equipamiento in  equipamientos_izquierdo %}
                       <li  class = "list-group-item" style='background-color: #1b9df5;' data-pk="{{equipamiento.pk}}">
                            {{equipamiento.equipamiento}}
                            {% if equipamiento.contain_detalle %}
                                <span class = "badge modal_class" data-pk="{{equipamiento.pk}}" ><a href="">Seguir leyendo </a></span>
                            {% endif %}
                       </li>
                    {% endfor %}

                    </ul>
              </div>

            <div class="col-md-4">
                    <ul class = "list-group">
                  {% for equipamiento in  equipamientos_central %}
                       <li  class = "list-group-item" style='background-color: #1b9df5;'>
                            {{equipamiento.equipamiento}}
                             {% if equipamiento.contain_detalle %}
                                <span class = "badge modal_class" data-pk="{{equipamiento.pk}}" ><a href="">Seguir leyendo </a></span>
                            {% endif %}
                       </li>
                    {% endfor %}

                    </ul>
            </div>


            <div class="col-md-4">
                    <ul class = "list-group">

                      {% for equipamiento in  equipamientos_derecho %}
                       <li   class = "list-group-item" style='background-color: #1b9df5;'>
                            {{equipamiento.equipamiento}}
                            {% if equipamiento.contain_detalle %}
                                <span class = "badge modal_class"  data-pk="{{equipamiento.pk}}"><a href="">Seguir leyendo </a></span>
                            {% endif %}
                       </li>
                    {% endfor %}

                    </ul>
            </div>

        </div>

        <div id="insert-modal">

        </div>
    </div>

{% endblock content %}


{% block jsfinal %}


    <script type="text/javascript">
        $(document).ready(function(){
            $('.modal_class').on('click', function(e){
              e.preventDefault();
              equipamiento_pk = $(this).data('pk');
              console.log('Equipamiento pk', equipamiento_pk);
                  $.ajax({
                      url: '{% url "web:ajax_equipamiento_modal" %}',
                      type: 'get',
                      data:{'equipamiento_pk': equipamiento_pk},

                      success: function(data){
                          $('#insert-modal').html(data);
                           $('#myModal').modal('show');
                      }
                  });

            });
        });
    </script>

{% endblock jsfinal %}

src/templates/web/equipamiento_ajax.html
<div class="modal fade" tabindex="-1" role="dialog" id='myModal' >
  <div class="modal-dialog" style="max-width: 1000px; width:auto; ">
    <div class="modal-content modal-color" style='background-color: #1b9df5;'>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="title_dev2">{{equipamiento.equipamiento}}</h4>
      </div>
      <div class="modal-body">

      {% for  detalle in detalles %}
        <p style="color: white;">{{detalle.detalle_equipamiento}}</p>
      {% endfor %}


      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

src/templates/web/historia.html
{% extends "common/_base.html" %}
{% load static %}

{% block content %}


    <div class="gallery">
        <div class="text-center">
            <h2 class="title_dev">{{historia.titulo}}</h2>
            <div class="parrafo_dev">
                    {{historia.texto|safe}}
            </div>
        </div>

    </div>
{% endblock content %}



{% block js_adicional %}
     <script type="text/javascript">

        $(document).ready(function() {
            console.log('HOLA MUNDO');

        });
    </script>

{% endblock js_adicional %}

src/templates/web/home.html
    {% extends "common/_base.html" %}
    {% load static %}
    {% load thumbnail %}

{% block content %}

    <div class="gallery">
        <div class="text-center">
            <h2 class="title_dev">{{home.titulo_bienvenida}}</h2>
            <div  class="parrafo_dev">
                {{home.texto_bienvenida|safe}}
            </div>
        </div>
        <div class="container">

        {% for servicio  in  servicios%}
            <div class="col-md-3">
            <a href="{{servicio.get_absolute_url}}">
                <figure class="effect-marley">
                    <img src="{{servicio.imagen_principal.path|thumbnail_by_name:'345x260'}}"  alt="" class="img-responsive" style="    width: 345px; height: 250px;" />
                    <figcaption>
                        <p>{{servicio.nombre}}</p>
                    </figcaption>
                </figure>
                </a>
            </div>
        {% endfor %}
        </div>

    </div>

    {% endblock content %}

src/templates/web/quienes_somos.html
{% extends "common/_base.html" %}
{% load static %}
{% load thumbnail %}
{% block content %}


    <div class="gallery">
        <div class="text-center">
            <h2 class="title_dev">{{quienes_somos.titulo_quienes_somos}}</h2>

            <div class="parrafo_dev">
                    {{quienes_somos.texto_quienes_somos|safe}}
            </div>

         </div>

    </div>

    <div class="gallery">
        <div class="text-center">
            <h1 class="title_dev text-left">{{quienes_somos.titulo_nuestros_socios}}</h1>

        </div>

        <div class="container">
             <div class="text-left">
                    <br>
                    <div class="col-md-6">
                    {% for otros in  otros_puestos_izquiedo%}
                        <li  class="parrafo_dev">{{otros.titulo_puesto}}</li>
                    {% endfor %}
                    </div>

                    <div class="col-md-6">
                    {% for otros in otros_puestos_derecho %}
                        <li  class="parrafo_dev">{{otros.titulo_puesto}}</li>
                    {% endfor %}
                    </div>
            </div>
        </div>

        <br>
        <br>
        <br>

        <div class="parrafo_dev">
                {{quienes_somos.texto_nuestros_socios|safe}}
        </div>

    </div>

    <br>
    <br>

    <div class="gallery">

    {% for  socio in  socios%}

        <div class="container">
            <div class="col-md-5">
                <figure class="effect-marley">
                    <img src="{{socio.imagen.path|thumbnail_by_name:'445x320'}}"  alt="" class="img-responsive" style=" width: 445; height: 320px;" />
                    <figcaption>
                        <p>{{socio.nombre}}</p>
                    </figcaption>
                </figure>
            </div>

            <div class="col-md-7 section_socios">
                    <div class="text-left">
                        <h2 class="title_dev">Nombre :</h2>
                        <p  class="parrafo_dev">{{socio.nombre}}</p>
                    </div>
                    <div class="text-left">
                        <h2 class="title_dev">Puesto :</h2>
                        <p  class="parrafo_dev">{{socio.puesto}}</p>
                    </div>
                    <div class="text-left">
                        <h2 class="title_dev">Logros :</h2>
                        {% for logro in  socio.logros_set.all%}
                        <li  class="parrafo_dev">{{logro.logro}}</li>

                        {% endfor %}


                    </div>
                    {% if socio.cv %}
                        <div>
                                 <a  href="{{socio.cv.url}}"  target="_blank" class="btn btn-info btn_dev">Descargar CV</a>
                        </div>
                    {% endif %}


            </div>
        </div>

    {% endfor %}

    </div>

{% endblock content %}

{% block js_adicional %}

      <script type="text/javascript">

        $(document).ready(function() {
            console.log('HOLA MUNDO');

        });
        </script>
{% endblock js_adicional %}